spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/senac_pedidos
    password: 601034
    username: postgres
    driverClassName: org.postgresql.Driver
